/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 .\public\models\wooden_floor.glb -t -r 
Author: cealford (https://sketchfab.com/cealford)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wooden-floor-54b0c7906b9047478aed14eb1b697f80
Title: Wooden Floor
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
  }
  materials: {
    floor_texture: THREE.MeshStandardMaterial
  }
}

export function Wooden_floor(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/wooden_floor.glb') as GLTFResult
  return (
    <group {...props} dispose={null} scale={0.01} position={[-0.5, 0.2, 0.6]}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.floor_texture} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/wooden_floor.glb')
